### ISSUE TITLE
can't cancel subscription to wharehouse

### ISSUE THREAD

**Issue by benzvi8888** [easyphp/WEBSITE#19]
this is an ethical bug, very important one. I wrote to you few times to cancel my subscription and you guys continue trying to charge my account, you do not have place to update, delete or change account. this is extremely not OK!

**Comment by easyphp** [comment]
Hi,
We checked but no email from you. Which email address did you use ?

**Comment by benzvi8888** [comment]
ben@digitalstudio5.com

**Comment by benzvi8888** [comment]
> Hi, We checked but no email from you. Which email address did you use ?
ben@digitalstudio5.com

**Comment by easyphp** [comment]
Hi,

We never received any email from that address asking for cancellation.
We cancelled the subscription.
Thanks for your support.

Best regards
